fix = true
show-fixes = true
target-version = "py312"

[format]
docstring-code-format = true

[lint]
ignore = [
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "D1",
  "ERA",
  "FIX",
  "INP",
  "ISC",
  "PLR09",
  "PLR2004",
  "RET504",
  "S",
  "T20",
  "TD",
]
select = ["ALL"]

[lint.flake8-import-conventions.extend-aliases]
"asyncio.subprocess" = "asp"
"subprocess" = "sp"

[lint.pydocstyle]
convention = "google"
