recipes:
  - name: ğŸ¤– AI
    providers:
      - dler-io:AI Suite
      - MetaCubeX/geosite:category-ai-!cn
      - SukkaW/classical:non_ip/ai

  - name: ğŸ¯ Direct
    providers:
      - blackmatrix7:Direct
      - dler-io:Special
      - liblaf:direct
      - SukkaW/classical:non_ip/direct

  - name: ğŸ“ Domestic
    providers:
      - blackmatrix7:ChinaMax
      - dler-io:Domestic
      - dler-io:Domestic IPs
      - MetaCubeX/geosite:cn
      - MetaCubeX/geosite:geolocation-cn
      - SukkaW/classical:ip/domestic
      - SukkaW/classical:non_ip/domestic

  - name: ğŸ“¥ Download
    providers:
      - SukkaW/classical:non_ip/cdn
      - SukkaW/classical:non_ip/download
      - SukkaW/domain:domainset/cdn
      - SukkaW/domain:domainset/download

  - name: ğŸŒ Global
    providers:
      - blackmatrix7:Global
      - dler-io:Proxy
      - MetaCubeX/geosite:geolocation-!cn
      - SukkaW/classical:non_ip/global

  - name: â™¾ï¸ Local
    providers:
      - blackmatrix7:Lan
      - dler-io:LAN
      - MetaCubeX/geosite:private
      - SukkaW/classical:ip/lan
      - SukkaW/classical:non_ip/lan

  - name: ğŸ“º Stream
    providers:
      - blackmatrix7:GlobalMedia
      - SukkaW/classical:ip/stream
      - SukkaW/classical:non_ip/stream

  - name: âœˆï¸ Telegram
    providers:
      - SukkaW/classical:ip/telegram
      - SukkaW/classical:non_ip/telegram
